### PR TITLE
Ubl 2.4 csd01wd02 handle bad gc

### PR DESCRIPTION
**Pull request by gkholman**

### CODE REVIEW

**Comment by gkholman** [comment]
It is difficult to test this now that the spreadsheet has been updated because there are NDR errors due to the spreadsheet contents. See the check*.html files in the archive-only subdirectory as indicated in the README.md file.

**Comment by gkholman** [comment]
Note also there is a spell check problem. Addressing this also is described in the README.md file.

**Comment by kduvekot** [comment]
@gkholman we can always break the spreadsheet again :-)

**Comment by kduvekot** [comment]
@gkholman looks like the spelling issue (Subtype vs SubType) is already fixed by @bdxhub

**Pull request merged**
